### ISSUE TITLE
Inquiry about Minimum VRAM Requirement for Text-to-Video Model

### ISSUE THREAD

**Issue by ninjasaid2k** [G-U-N/Gen-L-Video#1]
I would like to know the minimum VRAM requirement for the text-to-video model. Understanding this information will help me gauge the hardware requirements for running the model. Thank you for providing the details!

**Comment by G-U-N** [comment]
Hi, thanks for your interest. It actually depends on the choice of your short video diffusion models. If the code just runs correctly, it will not use more VRAM than a vanilla short video diffusion model. So, basically, for most experiments, RTX3090 should just work well.
