### ISSUE TITLE
accelerate launch one-shot-tuning.py --control=pose

### ISSUE THREAD

**Issue by ZHAOfan980914** [G-U-N/Gen-L-Video#10]
when i use accelerate launch one-shot-tuning.py --control=pose
![image](https://github.com/G-U-N/Gen-L-Video/assets/103413426/c76b92b6-267d-4f6f-bcb0-0f6da139870e)
can you help me to solve this issue?

**Comment by ZHAOfan980914** [comment]
![image](https://github.com/G-U-N/Gen-L-Video/assets/103413426/41a31b0d-431a-4c2b-ac46-d0a16fe0b513)

**Comment by ZHAOfan980914** [comment]
I have soveld the above issues

**Comment by G-U-N** [comment]
Hello, my apologies for the delayed response. I appreciate your patience. We have successfully resolved the initial issue, which originated from an incorrect placement of run_isolated. The subsequent challenge could potentially stem from a version discrepancy within imageio. Thank you for your understanding.

**Comment by treesturn** [comment]
> I have soveld the above issues

@ZHAOfan980914 Hi would u mind sharing how did u solve this problem, im facing the same issue, thank you
