### ISSUE TITLE
Question about the One-shot tuning Text-to-Video algorithm

### ISSUE THREAD

**Issue by fradino** [G-U-N/Gen-L-Video#12]
Hello, I have some question about the pipeline of One-shot tuning Text-to-Video algorithm. I am confused about how the algorithm below is reflected in the One-shot tuning code.
![image](https://github.com/G-U-N/Gen-L-Video/assets/31378961/5b969dfc-f267-4960-af2f-6bbb061b4f0d)
In the paper, it said 'The total number of frames of the video is S ∗ N + M'
In the code, the for loop is 'for i in range(0,video_length-clip_length+1,clip_length):'
Is it means S==M in this code?
Thank you very much!

**Comment by G-U-N** [comment]
When decoding with the VAE or run_isolated is set to true, S=M. 
When using `ddim_inversion_long` or `gen_long`, S = Stride, M=clip_length. 

And I just find a typo there, the total number of frames should be S*(N-1)+M. Thanks for your issue, and I will re-correct it when uploading a newer version.
