### ISSUE TITLE
git clone https://huggingface.co/andite/anything-v4.0. This address is currently inaccessible and cannot download relevant weight files. What should I do

### ISSUE THREAD

**Issue by QvQKing** [G-U-N/Gen-L-Video#18]
GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/andite/anything-v4.0
rm -rf ./anything-v4.0/**/*.bin
rm -rf ./anything-v4.0/**/*.safetensors
wget -P ./anything-v4.0/safety_checker/ https://huggingface.co/andite/anything-v4.0/resolve/main/safety_checker/model.safetensors
wget -P ./anything-v4.0/safety_checker/ https://huggingface.co/andite/anything-v4.0/resolve/main/safety_checker/pytorch_model.bin 
wget -P ./anything-v4.0/text_encoder/ https://huggingface.co/andite/anything-v4.0/resolve/main/text_encoder/model.safetensors
wget -P ./anything-v4.0/text_encoder/ https://huggingface.co/andite/anything-v4.0/resolve/main/text_encoder/pytorch_model.bin 
wget -P ./anything-v4.0/unet/ https://huggingface.co/andite/anything-v4.0/resolve/main/unet/diffusion_pytorch_model.bin
wget -P ./anything-v4.0/unet/ https://huggingface.co/andite/anything-v4.0/resolve/main/unet/diffusion_pytorch_model.safetensors
wget -P ./anything-v4.0/vae/ https://huggingface.co/andite/anything-v4.0/resolve/main/vae/diffusion_pytorch_model.bin
wget -P ./anything-v4.0/vae/ https://huggingface.co/andite/anything-v4.0/resolve/main/vae/diffusion_pytorch_model.safetensors

**Comment by G-U-N** [comment]
You can download the weights from this repo: https://huggingface.co/xyn-ai/anything-v4.0
